openapi: 3.0.0
info:
  title: Customer Microservice
  description: Customer Microservice
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/LINDERREYNAE/Customer-Microservice/1.0.0
    description: SwaggerHub API Auto Mocking
paths:
  /customer:
    post:
      tags:
        - customer
      summary: Add a new customer to the database
      description: Add a new customer to the database
      operationId: addCustomer
      requestBody:
        description: Create a new customer in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/xml:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        "405":
          description: Invalid input
  /customer/{id}:
    put:
      tags:
        - customer
      summary: Update an existing customer
      description: Update an existing customer by Id
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          description: ID of customer to update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent customer in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/xml:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: Invalid ID supplied
        "404":
          description: Customer not found
        "405":
          description: Validation exception
    get:
      tags:
        - customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: ID of customer to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
            application/xml:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid ID supplied
        "404":
          description: Customer not found
    delete:
      tags:
        - customer
      summary: Delete a customer
      description: delete a customer
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          description: Customer id to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "400":
          description: Invalid customer value
  /customer/dni/{dni}:
    get:
      tags:
        - customer
      summary: Find customer by DNI
      description: Returns a single customer
      operationId: getCustomerByDNI
      parameters:
        - name: dni
          in: path
          description: DNI of customer to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
            application/xml:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid DNI supplied
        "404":
          description: Customer not found
components:
  schemas:
    Response:
      type: object
      additionalProperties:
        type: object
    Customer:
      required:
        - dni
        - names
        - surnames
        - email
        - phone
        - afp
      type: object
      properties:
        id:
          type: string
        dni:
          type: string
          description: DNI
          minimum: 8
          maximum: 8
          pattern: '[0-9]{8}'
          example: "70000000"
        names:
          type: string
          description: Names
          pattern: '^(?=.{3,15}$)[A-ZÁÉÍÓÚ][a-zñáéíóú]+(?: [A-ZÁÉÍÓÚ][a-zñáéíóú]+)?$'
          example: Linder Jossemar
        surnames:
          type: string
          description: Surnames
          pattern: '^(?=.{3,15}$)[A-ZÁÉÍÓÚ][a-zñáéíóú]+(?: [A-ZÁÉÍÓÚ][a-zñáéíóú]+)?$'
          example: Reyna Esquivel
        email:
          type: string
          description: email
          pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$'
          example: linder_reynae@hotmail.com
        phone:
          type: string
          description: phone
          pattern: '(\+51|51|)[0-9]+'
          example: "+51940000000"
        afp:
          type: string
          description: AFPs
          example: HABITAT
        amountAvailable:
          type: number
          format: currency
          description: amount available
          example: 1000.00
          default: 0.00
      xml:
        name: customer
  requestBodies:
    customer:
      description: customer object that needs to be added to the database
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Customer'
        application/xml:
          schema:
            $ref: '#/components/schemas/Customer'